FROM node:18

WORKDIR /app

# Install dependencies
COPY spydra-front/package.json spydra-front/package-lock.json ./
RUN npm install

# Copy application code
COPY spydra-front/ .

# Expose port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]